# Create and Publish repository Packages

name: Publish Packages for Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Publish Release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Check Build
        run: ./gradlew check --warn
        timeout-minutes: 7

      - name: Generate JavaDoc
        run: ./gradlew dokkaJavadoc --warn
        if: success()
        timeout-minutes: 3

      - name: Publish Packages
        run: ./gradlew publish --warn
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JavaDoc
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: DecimalPlaces-JavaDocs
          path: |
            /home/runner/work/*/*/queue/build/dokka/
          retention-days: 28
        timeout-minutes: 1